services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RozbehSharahi\Graphql3\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  RozbehSharahi\Graphql3\Registry\SchemaRegistry:
    public: true

  RozbehSharahi\Graphql3\Registry\QueryFieldRegistry:
    public: true

  RozbehSharahi\Graphql3\Type\:
    resource: '../Classes/Type/*'
    public: true
