services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RozbehSharahi\Graphql3\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  RozbehSharahi\Graphql3\Middleware\GraphqlRequestMiddleware:
    arguments:
      $setups: !tagged_iterator graphql3.setup

  RozbehSharahi\Graphql3\Type\QueryType:
    arguments:
      $extenders: !tagged_iterator graphql3.query_type_extender

  RozbehSharahi\Graphql3\Type\MutationType:
    arguments:
      $extenders: !tagged_iterator graphql3.mutation_type_extender

  RozbehSharahi\Graphql3\Builder\RecordNodeBuilder:
    arguments:
      $extenders: !tagged_iterator graphql3.record_node_extender

  RozbehSharahi\Graphql3\Builder\RecordListNodeBuilder:
    arguments:
      $extenders: !tagged_iterator graphql3.record_list_node_extender

  RozbehSharahi\Graphql3\Resolver\RecordListResolver:
    arguments:
      $extenders: !tagged_iterator graphql3.record_list_resolver_extender

  RozbehSharahi\Graphql3\Security\AccessChecker:
    arguments:
      $voters: !tagged_iterator graphql3.voter

  RozbehSharahi\Graphql3\Builder\RecordTypeBuilder:
    arguments:
      $fieldCreators: !tagged_iterator { tag: graphql3.field_creator, default_priority_method: getPriority }
      $flexFormFieldCreators: !tagged_iterator { tag: graphql3.flex_form_field_creator, default_priority_method: getPriority }
      $extenders: !tagged_iterator graphql3.record_type_builder_extender

  RozbehSharahi\Graphql3\Command\CreateTokenManualCommand:
    tags:
      - { name: console.command, command: 'graphql3:create-token:manual' }

  RozbehSharahi\Graphql3\Command\CreateTokenFrontendUserCommand:
    tags:
      - { name: console.command, command: 'graphql3:create-token:frontend-user' }