services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RozbehSharahi\Graphql3\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  RozbehSharahi\Graphql3\Registry\SiteSchemaRegistry:
    public: true
