services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RozbehSharahi\Graphql3\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  RozbehSharahi\Graphql3\Middleware\GraphqlRequestMiddleware:
    arguments:
      $setups: !tagged_iterator graphql3.setup

  RozbehSharahi\Graphql3\Type\QueryType:
    arguments:
      $extenders: !tagged_iterator graphql3.query_type_extender

  RozbehSharahi\Graphql3\Type\PageType:
    arguments:
      $extenders: !tagged_iterator graphql3.page_type_extender

  RozbehSharahi\Graphql3\Node\PageNode:
    arguments:
      $extenders: !tagged_iterator graphql3.page_node_extender

  RozbehSharahi\Graphql3\Resolver\PageResolver:
    arguments:
      $extenders: !tagged_iterator graphql3.page_node_extender

  RozbehSharahi\Graphql3\Security\AccessChecker:
    arguments:
      $voters: !tagged_iterator graphql3.voter
