name: GitHub Actions | Pipeline
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['12.4', '13.4']

    env:
      GRAPHQL3_JWT_PRIVATE_KEY: "file://Tests/Fixture/KeyPairs/Rs256/private.pem"
      GRAPHQL3_JWT_PUBLIC_KEY: "file://Tests/Fixture/KeyPairs/Rs256/public.pem"

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, sqlite3, intl-70.1
      - uses: actions/checkout@v3
      - run: sed -i 's/\^12\.4 || \^13\.4/^${{ matrix.version }}/g' composer.json
      - run: composer install
      - run: tools/php-cs-fixer fix --dry-run
      - run: vendor/bin/phpstan
      - run: vendor/bin/phpunit

  publish:
    needs: tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check tag
        run: |
          if ! [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3} ]]; then
            exit 1
          fi

      - name: Get version
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

      - name: Get comment
        id: get-comment
        run: |
          readonly local comment=$(git tag -n10 -l v${{ steps.get-version.outputs.version }} | sed "s/^[0-9.]*[ ]*//g")

          if [[ -z "${comment// }" ]]; then
            echo ::set-output name=comment::Released version ${{ steps.get-version.outputs.version }} of ${{ env.TYPO3_EXTENSION_KEY }}
          else
            echo ::set-output name=comment::$comment
          fi

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2

      - name: Install tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Publish to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --comment "${{ steps.get-comment.outputs.comment }}" ${{ steps.get-version.outputs.version }}